USE Retail_Interaction_SQL;

-- 1. How has customer registration changed year over year?

SELECT year,COUNT(*) AS Total_Customers
FROM customer
GROUP BY year
ORDER BY year;

-- Outcome:- Every Year almost 10-15 less customer register


-- 2. What percentage of customers are repeat buyers?

SELECT 
    COUNT(DISTINCT CASE WHEN cnt > 1 THEN customer_id END) * 100.0 
    / COUNT(DISTINCT customer_id) AS Repeat_Buyer_Percentage
FROM (
    SELECT customer_id, COUNT(*) AS cnt
    FROM [transaction]
    GROUP BY customer_id
) t; 

-- Outcome:- Almost 91% customers buy more than one


-- 3. Which customer age group contributes the highest revenue?

SELECT TOP 1 age_group,
       SUM(total_spent) * 100.0 / 
       (SELECT SUM(total_spent) FROM customer) AS Total_Revenue_By_Age_Group
FROM customer
GROUP BY age_group
ORDER BY SUM(total_spent) DESC;

-- Outcome:- 46.2% Revenue is generated by people of age_group 18-35


-- 4. Which states generate the most revenue?

SELECT TOP 1 state,
        SUM(total_spent) * 100.0 /
        (SELECT SUM(total_spent) FROM customer) AS State_Revenue_Percentage
FROM customer
GROUP BY state
ORDER BY SUM(total_spent) DESC;

-- Outcome:- California generate most revenue(around 18.4%)


-- 5. What is the average revenue per customer?

SELECT AVG(total_spent) AS Avg_Revenue FROM customer;

-- Outcome:- Avg revenue is 5421


-- 6. How many viewers (interaction users) converted into buyers?

SELECT COUNT(DISTINCT i.customer_id) * 100.0 /
        (SELECT COUNT(DISTINCT customer_id) FROM interaction) AS Viewer_To_Buyer_Conversion
FROM interaction i
INNER JOIN [transaction] t ON i.customer_id=t.customer_id;

-- Outcome:- 92.3% viewers are also buyers


